version: "3.9"

services:
  market-app:
    build: ./market
    container_name: market-app
    volumes:
      - ./offering_images:/app/images
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - IMAGE_DIRECTORY=/app/images
      - PAYMENT_SERVICE_URL=http://payment-service:8080
      - SPRING_DATA_REDIS_HOST=redis-server
      - SPRING_DATA_REDIS_PORT=6379
      - AUTH_SERVER_URL=http://authentication-server:8080
      - MARKET_APP_SECRET=${MARKET_APP_SECRET}
    depends_on:
      authentication-server:
        condition: service_healthy
      redis-server:
        condition: service_started

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - AUTH_SERVER_URL=http://authentication-server:8080
    depends_on:
      authentication-server:
        condition: service_healthy

  redis-server:
    container_name: redis-server
    image: redis:7.4.2-bookworm
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    restart: unless-stopped

  authentication-server:
    image: keycloak/keycloak:26.4
    container_name: authentication-server
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_DRIVER: org.postgresql.Driver
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8082:8080"
      - "9000:9000"
    depends_on:
      - postgres
    command:
      - start-dev
      - --health-enabled=true
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s