version: "3.9"

services:
  market-app:
    build: ./market
    container_name: market-app
    volumes:
      - ./offering_images:/app/images
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - IMAGE_DIRECTORY=/app/images

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8081:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}