spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 30
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:${IMAGE_DIRECTORY}

offering:
  images-directory: ${IMAGE_DIRECTORY}

logging:
  level:
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG